config/routes.rb
Rails.application.routes.draw do
  get 'admin_user/list'

  get 'admin_user/new'

  get 'admin_user/edit'

  get 'admin_user/delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :username, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin_user_controller.rb
class AdminUserController < ApplicationController
  # layout 'admin'

  # before_filter :confirm_logged_on

  def index
    list
    render :list
  end

  def list
    # @admin_users = AdminUser.sorted
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(params[:admin_user])
    if @admin_user.save
      flash[:notice] = "Admin successfully added"
      redirect_to list_path
    else
      flash[:alert] = "The admin was not added. Try again!"
      render :new
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update
      flash[:notice] = "Admin successfully editted"
      redirect_to list_path
    else
      flash[:alert] = "The admin was not editted. Try again!"
      render :edit
    end
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    flash[:notice] = "Admin successfully deleted!"
    redirect_to list_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admin_user_helper.rb
module AdminUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin_user/_form.html.erb
<%= form_for @admin_user do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>

	<%= f.label :username %>
	<%= f.text_field :username %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.submit %>
<% end %>

app/views/admin_user/delete.html.erb
<h1>AdminUser#delete</h1>
<p>Find me in app/views/admin_user/delete.html.erb</p>

app/views/admin_user/edit.html.erb
<%content_for(:title, "Edit Admin") %>

<h2>Edit Admin's Details</h2>

<%= render "form"%>

app/views/admin_user/list.html.erb
<h2>Admin Users</h2>

<ul>
	<% @admin_users.each do |admin_user| %>
		<li><%= admin_user.first_name %></li>
	<% end %>
</ul>

<% link_to "Add New Admin", new_admin_user_path %>
<% link_to "Add New Admin", new_admin_user_path %>

app/views/admin_user/new.html.erb
<%content_for(:title, "New Admin") %>

<h2>Add A New Admin</h2>

<%= render "form"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPersonalPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>